#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true
skip_branch_with_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# fetch repository as zip archive
shallow_clone: true

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - cmd: cd src
  - cmd: nuget restore
  - cmd: cd ..

# build settings themselves
build:
  project: src/Cyberkruz.sln
  verbosity: minimal
  publish_wap: true

deploy:
  - provider: WebDeploy
    server: https://cyberkruz-aspnet-starterkit-stage.scm.azurewebsites.net:443/msdeploy.axd?site=cyberkruz-aspnet-starterkit__stage
    website: cyberkruz-aspnet-starterkit__stage
    username: 
      secure: WrCSOhp5wdBM0A3QxxdZHhZA2jgFL6MlkPjDFy9jlLd7/gmfQdFUzn8xKJIGrUww
    password: 
      secure: bUHMqcyFYrqC12tt/ivdUuuMcJ1Ck4+TlE0eKtqSTucNy0T9uznRN9/9qVdxSOduo1fG+5cKMsYD8+k/FLgCfA==
    ntlm: false
    remove_files: true
    on:
      branch: master
