version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_branch_with_pr: true

image: Visual Studio 2015

clone_depth: 4

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

configuration: Release

before_build:
  - cmd: cd src
  - cmd: nuget restore
  - cmd: cd ..

build:
  project: src/Cyberkruz.sln
  verbosity: minimal
  publish_wap: true

deploy:
  - provider: WebDeploy
    server: https://cyberkruz-aspnet-starterkit-stage.scm.azurewebsites.net:443/msdeploy.axd?site=cyberkruz-aspnet-starterkit__stage
    website: cyberkruz-aspnet-starterkit__stage
    username: 
      secure: WrCSOhp5wdBM0A3QxxdZHhZA2jgFL6MlkPjDFy9jlLd7/gmfQdFUzn8xKJIGrUww
    password: 
      secure: bUHMqcyFYrqC12tt/ivdUuuMcJ1Ck4+TlE0eKtqSTucNy0T9uznRN9/9qVdxSOduo1fG+5cKMsYD8+k/FLgCfA==
    ntlm: false
    remove_files: true
    on:
      branch: master
      appveyor_repo_tag: false
  
  - provider: WebDeploy
    server: https://cyberkruz-aspnet-starterkit-prod.scm.azurewebsites.net:443/msdeploy.axd?site=cyberkruz-aspnet-starterkit__prod
    website: cyberkruz-aspnet-starterkit__prod
    username:
      secure: WrCSOhp5wdBM0A3QxxdZHhc2pucgdMypgVuTa/+/uij2uGiaShTu+UmHEOHbVG0L
    password:
      secure: CeJ3IIRrS+p7scPp8nXsOXnu2luLbrlntNNmYrcvQWnZdcmsF4tmELSW2h+i2T507j3BwAQ7KHb5E4X2c6V/ow==
    ntlm: false
    remove_files: true
    on:
      appveyor_repo_tag: true